Algoritmo "teste jogo
"



var

   qtdTimes, cont, possivel: inteiro
   time1, time2, time3, time4 : caractere

Inicio

   escreval("Quantidade de times: ")
   leia(qtdTimes)
   
   escreval("Times: ")
   leia(time1)
   possivel <- 2 ^ qtdTimes
   escolha qtdTimes
     caso 2
     leia(time2)
     caso 3
     leia(time2, time3)
     caso 4
     leia(time2, time3, time4)
   fimescolha
   
   enquanto  cont

   
   fimenquanto
   
   

   





Fimalgoritmo
